# Generated by Django 2.1.3 on 2018-12-07 08:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ddit_assets_log',
            },
        ),
        migrations.CreateModel(
            name='Company_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='创建时间')),
                ('name', models.CharField(default='无', max_length=128, verbose_name='供货商公司名')),
                ('contacts', models.CharField(default='无', max_length=128, verbose_name='联系人')),
                ('phone', models.CharField(max_length=32, verbose_name='电话号码')),
                ('type', models.CharField(max_length=32, verbose_name='职能所属')),
                ('Address', models.CharField(max_length=128, verbose_name='地址')),
                ('bill', models.CharField(max_length=32, verbose_name='开票类型')),
                ('buyer', models.CharField(max_length=128, verbose_name='采购类别')),
            ],
            options={
                'db_table': 'ddit_company',
            },
        ),
        migrations.CreateModel(
            name='create_vm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='创建时间')),
                ('proposer', models.CharField(max_length=128, verbose_name='申请人')),
                ('dept', models.CharField(max_length=128, verbose_name='申请人部门')),
                ('name', models.UUIDField(verbose_name='机器名')),
                ('host_ip', models.GenericIPAddressField(null=True, verbose_name='宿主机IP地址')),
                ('vm_ip', models.GenericIPAddressField(null=True, verbose_name='虚拟机IP地址')),
                ('cpus', models.SmallIntegerField(verbose_name='CPU个数')),
                ('memory', models.SmallIntegerField(verbose_name='内存大小')),
                ('disk', models.CharField(max_length=128, verbose_name='硬盘大小')),
                ('type', models.CharField(max_length=128, verbose_name='机器类型')),
                ('os_type', models.CharField(max_length=128, verbose_name='机器类型')),
                ('end_time', models.DateField(null=True, verbose_name='到期日期')),
                ('on_line', models.BooleanField(verbose_name='永久生效')),
            ],
            options={
                'db_table': 'ddit_create_vm',
            },
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arr1', models.CharField(default='DDIT', max_length=4)),
                ('arr2', models.CharField(max_length=4, unique=True)),
                ('arr3', models.CharField(max_length=6, null=True)),
                ('cname', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'ddit_dict',
            },
        ),
        migrations.CreateModel(
            name='FAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_created=True, auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, null=True)),
                ('asset_user', models.CharField(max_length=128, verbose_name='领用人')),
            ],
            options={
                'db_table': 'ddit_assets',
            },
        ),
        migrations.CreateModel(
            name='host_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=128, null=True, verbose_name='设备名称')),
                ('type', models.CharField(max_length=128, null=True, verbose_name='设备类型')),
                ('CPU', models.CharField(max_length=128, null=True, verbose_name='CPU型号')),
                ('Memory', models.CharField(max_length=128, null=True, verbose_name='内存型号')),
                ('Bios', models.CharField(max_length=128, null=True, verbose_name='主板型号')),
                ('MAC', models.CharField(max_length=128, null=True, unique=True, verbose_name='mac地址')),
                ('SN', models.CharField(max_length=128, null=True, verbose_name='S/N')),
                ('NETWORK', models.CharField(max_length=128, null=True, verbose_name='网卡型号')),
                ('CDrom', models.CharField(max_length=128, null=True, verbose_name='光驱型号')),
                ('Video', models.CharField(max_length=128, null=True, verbose_name='显卡型号')),
                ('Sound', models.CharField(max_length=128, null=True, verbose_name='声卡型号')),
                ('Disk', models.CharField(max_length=128, null=True, verbose_name='硬盘')),
                ('Display', models.CharField(max_length=128, null=True, verbose_name='显示器')),
            ],
        ),
        migrations.CreateModel(
            name='log_system_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=128, verbose_name='操作类型')),
                ('opeater', models.CharField(max_length=128, verbose_name='操作人员')),
                ('type', models.CharField(max_length=128, verbose_name='操作类型')),
                ('info', models.CharField(max_length=128, verbose_name='操作日志')),
            ],
            options={
                'db_table': 'ddit_system_info',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=128, verbose_name='菜单别名')),
                ('url', models.CharField(max_length=128, null=True, verbose_name='链接地址')),
                ('name', models.CharField(max_length=128, verbose_name='菜单名')),
                ('top', models.SmallIntegerField(null=True, verbose_name='菜单')),
                ('child', models.SmallIntegerField(null=True, verbose_name='二级菜单')),
                ('top_no', models.SmallIntegerField(null=True, verbose_name='父级菜单ID')),
            ],
            options={
                'db_table': 'ddit_menu',
            },
        ),
        migrations.CreateModel(
            name='open_port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='创建时间')),
                ('start_time', models.DateField(auto_created=True, auto_now_add=True, verbose_name='开始日期')),
                ('proposer', models.CharField(max_length=128, verbose_name='申请人')),
                ('dept', models.CharField(max_length=128, verbose_name='申请人部门')),
                ('rule_name', models.CharField(max_length=128, unique=True, verbose_name='策略名')),
                ('desc', models.CharField(max_length=128, verbose_name='策略用途')),
                ('host_ip', models.GenericIPAddressField(verbose_name='ip地址')),
                ('type', models.CharField(max_length=32, verbose_name='协议类型')),
                ('inside_port', models.CharField(max_length=32, verbose_name='内网端口号')),
                ('outside_port', models.CharField(max_length=32, verbose_name='外网端口号')),
                ('end_time', models.DateField(null=True, verbose_name='到期日期')),
                ('on_line', models.CharField(max_length=32, null=True, verbose_name='永久生效')),
                ('interface', models.CharField(max_length=128, verbose_name='接口名')),
            ],
            options={
                'db_table': 'ddit_open_port',
            },
        ),
        migrations.CreateModel(
            name='period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=128, null=True, verbose_name='任务名称')),
                ('start_at', models.CharField(max_length=128, null=True, verbose_name='开始时间')),
                ('end_at', models.CharField(max_length=128, null=True, verbose_name='结束时间')),
                ('delay', models.CharField(max_length=128, null=True, verbose_name='延期时间')),
                ('plan_no', models.CharField(max_length=128, null=True, verbose_name='预期工作量')),
                ('fact_no', models.CharField(max_length=128, null=True, verbose_name='实际工作量')),
                ('Evaluation', models.CharField(max_length=128, null=True, verbose_name='考评内容')),
            ],
            options={
                'db_table': 'ddit_period',
            },
        ),
        migrations.CreateModel(
            name='PM_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='创建时间')),
                ('contract_id', models.CharField(max_length=128, null=True, verbose_name='合同编号')),
                ('contract_start', models.CharField(max_length=128, null=True, verbose_name='合同开始日期')),
                ('contract_end', models.CharField(max_length=128, null=True, verbose_name='合同结束日期')),
                ('contract_price', models.CharField(max_length=128, null=True, verbose_name='合同金额')),
                ('contract_work', models.CharField(max_length=128, null=True, verbose_name='预期工作量')),
                ('pid', models.CharField(max_length=128, unique=True, verbose_name='项目编号')),
                ('father_name', models.CharField(max_length=128, verbose_name='项目名称')),
                ('child_name', models.CharField(max_length=128, verbose_name='项目二级分类')),
                ('service2in', models.CharField(max_length=128, null=True, verbose_name='业务线标识in')),
                ('service2out', models.CharField(max_length=128, null=True, verbose_name='业务线标识out')),
                ('operator', models.CharField(max_length=128, verbose_name='执行方')),
                ('manager', models.CharField(max_length=128, verbose_name='责任方')),
                ('date_time', models.CharField(max_length=128, null=True, verbose_name='上线时间')),
                ('Manage', models.CharField(max_length=128, null=True, verbose_name='PM')),
                ('step', models.CharField(max_length=10, verbose_name='当前阶段')),
                ('desc', models.CharField(max_length=128, null=True, verbose_name='备注说明')),
            ],
            options={
                'db_table': 'ddit_PM_list',
            },
        ),
        migrations.CreateModel(
            name='Reserves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=128, verbose_name='资产名')),
                ('Type', models.CharField(max_length=32, verbose_name='资产类别')),
                ('asset_No', models.CharField(max_length=128, unique=True, verbose_name='设备编码')),
                ('price', models.SmallIntegerField(verbose_name='资产价格')),
                ('company', models.CharField(max_length=128, verbose_name='供应商')),
                ('contacts', models.CharField(max_length=128, verbose_name='联系人')),
                ('manger_user', models.CharField(max_length=128, verbose_name='管理人')),
                ('status', models.CharField(max_length=32, verbose_name='资产状态')),
                ('info', models.ForeignKey(on_delete=None, related_name='host', to='db_server.host_info')),
            ],
            options={
                'db_table': 'ddit_reserves',
            },
        ),
        migrations.CreateModel(
            name='Role2Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(null=True, on_delete=None, related_name='menu', to='db_server.Menu')),
                ('rid', models.ForeignKey(null=True, on_delete=None, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ddit_Role2Menu',
            },
        ),
        migrations.CreateModel(
            name='Server_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=32, verbose_name='服务器名称')),
                ('IP', models.GenericIPAddressField(unique=True, verbose_name='IP地址')),
                ('OS', models.CharField(max_length=128, null=True, verbose_name='操作系统类型')),
                ('desric', models.CharField(max_length=128, null=True, verbose_name='说明')),
                ('status', models.CharField(max_length=128, null=True, verbose_name='服务器状态')),
                ('server', models.CharField(max_length=4, null=True, verbose_name='服务器类型')),
                ('true_server', models.CharField(max_length=128, null=True, verbose_name='宿主机')),
            ],
            options={
                'db_table': 'ddit_server_info',
            },
        ),
        migrations.CreateModel(
            name='Work_hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='更新时间')),
                ('create_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='创建时间')),
                ('arr1', models.FloatField(null=True, verbose_name='1月数据')),
                ('arr2', models.FloatField(null=True, verbose_name='2月数据')),
                ('arr3', models.FloatField(null=True, verbose_name='3月数据')),
                ('arr4', models.FloatField(null=True, verbose_name='4月数据')),
                ('arr5', models.FloatField(null=True, verbose_name='5月数据')),
                ('arr6', models.FloatField(null=True, verbose_name='6月数据')),
                ('arr7', models.FloatField(null=True, verbose_name='7月数据')),
                ('arr8', models.FloatField(null=True, verbose_name='8月数据')),
                ('arr9', models.FloatField(null=True, verbose_name='9月数据')),
                ('arr10', models.FloatField(null=True, verbose_name='10月数据')),
                ('arr11', models.FloatField(null=True, verbose_name='11月数据')),
                ('arr12', models.FloatField(null=True, verbose_name='12月数据')),
                ('date', models.CharField(max_length=32, null=True, verbose_name='年份')),
                ('item', models.ForeignKey(null=True, on_delete=None, related_name='pm_id', to='db_server.PM_list')),
            ],
            options={
                'db_table': 'ddit_Work_hours',
            },
        ),
        migrations.AddField(
            model_name='period',
            name='no',
            field=models.ForeignKey(on_delete=None, related_name='No', to='db_server.PM_list', verbose_name='项目编号'),
        ),
        migrations.AddField(
            model_name='fassets',
            name='asset_info',
            field=models.ForeignKey(on_delete=None, related_name='no', to='db_server.Reserves'),
        ),
    ]
