# Generated by Django 2.1.3 on 2018-12-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_server', '0002_monitor_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserves',
            name='finance_id',
            field=models.CharField(max_length=128, null=True, verbose_name='财务对应资产编号'),
        ),
    ]
