# Generated by Django 2.1.3 on 2018-12-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_server', '0003_reserves_finance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor_host',
            name='on_line',
            field=models.CharField(default=123213, max_length=256, verbose_name='状态'),
            preserve_default=False,
        ),
    ]
