# Generated by Django 2.1.3 on 2018-12-11 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db_server', '0006_auto_20181211_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_system_info',
            name='create_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
    ]
