# Generated by Django 2.1.3 on 2018-12-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_server', '0007_log_system_info_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='monitor_stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.FloatField(null=True, verbose_name='CPU百分比')),
                ('meminfo', models.FloatField(null=True, verbose_name='内存百分比')),
                ('diskinfo', models.FloatField(null=True, verbose_name='磁盘百分比')),
                ('netinfo', models.FloatField(null=True, verbose_name='网络百分比')),
                ('create_at', models.DateTimeField(null=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'ddit_monitor_stat',
            },
        ),
        migrations.RemoveField(
            model_name='monitor_host',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='monitor_host',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='monitor_host',
            name='diskinfo',
        ),
        migrations.RemoveField(
            model_name='monitor_host',
            name='meminfo',
        ),
        migrations.RemoveField(
            model_name='monitor_host',
            name='netinfo',
        ),
        migrations.AddField(
            model_name='monitor_stat',
            name='host_id',
            field=models.ForeignKey(on_delete=None, related_name='host', to='db_server.monitor_host'),
        ),
    ]
