# Generated by Django 2.1.3 on 2018-12-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_server', '0008_auto_20181212_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor_stat',
            name='cpu',
            field=models.CharField(max_length=128, null=True, verbose_name='CPU百分比'),
        ),
        migrations.AlterField(
            model_name='monitor_stat',
            name='create_at',
            field=models.DateTimeField(max_length=128, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='monitor_stat',
            name='diskinfo',
            field=models.CharField(max_length=128, null=True, verbose_name='磁盘百分比'),
        ),
        migrations.AlterField(
            model_name='monitor_stat',
            name='meminfo',
            field=models.CharField(max_length=128, null=True, verbose_name='内存百分比'),
        ),
        migrations.AlterField(
            model_name='monitor_stat',
            name='netinfo',
            field=models.CharField(max_length=128, null=True, verbose_name='网络百分比'),
        ),
    ]
