# Generated by Django 2.1.3 on 2018-12-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_server', '0009_auto_20181212_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_system_info',
            name='host',
            field=models.CharField(default=1231, max_length=128, verbose_name='执行主机'),
            preserve_default=False,
        ),
    ]
