# Generated by Django 2.1.3 on 2018-12-13 04:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db_server', '0010_log_system_info_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor_stat',
            name='host_id',
        ),
        migrations.AddField(
            model_name='monitor_host',
            name='create_at',
            field=models.DateTimeField(max_length=128, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='monitor_stat',
            name='ip',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='主机地址'),
            preserve_default=False,
        ),
    ]
