# Generated by Django 2.1.3 on 2018-12-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_server', '0011_auto_20181213_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='log_vm_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='创建时间')),
                ('action_type', models.CharField(max_length=128, verbose_name='操作类型')),
                ('opeater', models.CharField(max_length=128, verbose_name='操作人员')),
                ('type', models.CharField(max_length=128, verbose_name='操作类型')),
                ('info', models.CharField(max_length=128, verbose_name='操作日志')),
                ('host', models.CharField(max_length=128, verbose_name='执行主机')),
            ],
            options={
                'db_table': 'ddit_vm_info',
            },
        ),
        migrations.AddField(
            model_name='server_info',
            name='type',
            field=models.CharField(max_length=128, null=True, verbose_name='虚拟化技术类型'),
        ),
    ]
